- name: Do basic setup
  hosts: all
  tasks:
 
    - name: Get GPG keys for RVM install package
      shell: curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable
      args:
        warn: false

    - name: Create directory for repositories
      shell: mkdir -p {{ ansible_env.HOME }}/Repos

    - name: Install seclists wordlists
      git:
          repo: git@github.com:danielmiessler/SecLists.git
          dest: '{{ ansible_env.HOME }}/Repos/SecLists'

    - name: Configure zsh autosuggest strategy
      shell: echo ZSH_AUTOSUGGEST_STRATEGY=match_prev_cmd >> ~/.zshrc.local

    - name: Configure zsh history dups
      shell: echo HIST_IGNORE_ALL_DUPS="false" >> ~/.zshrc.local && echo HIST_EXPIRE_DUPS_FIRST="true" >> ~/.zshrc.local

    - name: Configure zsh beeps
      shell: echo "unsetopt LIST_BEEP" >> ~/.zshrc.local
    
    - name: Tell git who I am
      shell: git config --global user.email "dmsilva@protonmail.com" && git config --global user.name "Dario Martins Silva"

