- name: hashcat
  hosts: all
  tasks:
    - name: "clone repository"
      git:
        accept_hostkey: yes
        clone: yes
        depth: 1
        dest: /tmp/hashcat
        force: yes
        repo: https://github.com/hashcat/hashcat.git

    - name: "build"
      make:
        chdir: /tmp/hashcat

    - name: "hashcat : install"
      make:
        chdir: /tmp/hashcat
        target: install

    - name: "hashcat : create data directory"
      file:
        path: /usr/share/hashcat
        state: directory

    - name: "hashcat : copy data files"
      synchronize:
        dest: /usr/share/hashcat
        src: "/tmp/hashcat/{{ item }}"
      with_items:
        - rules
        - masks
        - charsets

    - name: "cleanup"
      file:
        path: /tmp/hashcat
        state: absent
