- name: Metasploit
  hosts: all
  tasks:
    - name: Install Metasploit
      shell: 'curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall'
      args:
        chdir: /tmp
        executable: /usr/bin/zsh
