- name: pwndbg
  hosts: all
  tasks:

    - name: Clone Repository
      git:
        repo: https://github.com/pwndbg/pwndbg
        dest: "{{ ansible_env.HOME }}/Repos/pwndbg"
    - name: Run pwndbg setupscript
      shell: ./setup.sh
      args:
        chdir: "{{ ansible_env.HOME }}/Repos/pwndbg"
        executable: /usr/bin/zsh
