- name: Install basic software
  hosts: all
  tasks:
    - name: Update repositories cache and install deps
      apt:
        name:
          - git
          - git-extras
          - python2
          - python3
          - curl
          - tmux
          - htop
          - python-pip
          - strace
          - mosh
          - golang
          - pipenv
          - vim-gtk
          - silversearcher-ag
          - nmap
          - hashid
          - xclip
          - cherrytree 
        update_cache: yes
